#项目配置
cenhai:
  #名称
  name: cenhai
  #版本
  version: 1.0
  #文件路径
  profile: /Users/cenjihai/temp
  #profile: /www/wwwroot/temp
#插件开发配置
plugin:
  # 开启解密校检
  decrypt:
    enable: true
    className: com.gitee.starblues.common.cipher.AesPluginCipher
    props:
      secretKey: mmfvXes1XckCi8F/y9i0uQ==
  runMode: prod
  mainPackage: com.cenhai
  pluginPath:
    - /Users/cenjihai/temp/plugins
    #- /www/wwwroot/temp/plugins
  backupPath: /Users/cenjihai/temp/backup
  #backupPath: /www/wwwroot/temp/backup
server:
  port: 8080
spring:
  application:
    name: admin
  profiles:
    active: druid
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.cenhai.**.domain
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    local-cache-scope: session
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1
      logic-delete-field: deleted
#分页参数合理化
pagehelper:
  reasonable: true
#jwt token配置
token:
  header: Authorization
  secret: dasd12s3ad1a23
  expireTime: 300