#项目配置
cenhai:
  #名称
  name: cenhai
  #版本
  version: 1.0
  #文件路径
  profile: D://home

#插件开发配置
plugin:
  # 开启解密校检
  decrypt:
    enable: true
    className: com.gitee.starblues.common.cipher.AesPluginCipher
    props:
      secretKey: mmfvXes1XckCi8F/y9i0uQ==
  runMode: prod
  mainPackage: com.cenhai
  pluginPath:
    - D:\home\plugins
  backupPath: D:\home\temp
server:
  port: 8080
spring:
  application:
    name: admin
  profiles:
    active: druid
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
mybatis-plus:
  type-aliases-package: com.cenhai.*.domain
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
token:
  header: Authorization
  secret: dasd12s3ad1a23
  expireTime: 300